apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  DB_HOST: "production-mysql-db.cw3ww0gegq7w.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "production-mysql-db"
  REACT_APP_API_URL: http://backend-service:8080
